#!/bin/bash

STYLE="Hand-drawn stick figure illustration style inspired by the YouTube channel Zenn. Simple stick figures with round heads, dot eyes, and expressive body language. Rich vibrant colourful backgrounds — deep dark blue and purple space backgrounds packed with bright white stars, glowing planets, silver rockets and space stations. Lots of colour — bright yellows, electric blues, vivid purples, warm oranges, glowing greens. Bold black outlines on all figures and objects. Wobbly hand-drawn feel but colourful and lively. Red arrows and handwritten labels for emphasis. Every scene feels alive with colour and energy. Not realistic, not 3D, not photographic. Charming, expressive and packed with colour."

mkdir -p output_glass

gen() {
  local num=$1
  local prompt=$2
  local attempts=0
  echo "Generating image $num..."
  until higgsfield generate create nano_banana_2 --prompt "${STYLE} ${prompt}" --wait > "output_glass/image_${num}.txt" 2>&1 && grep -q "http" "output_glass/image_${num}.txt"; do
    attempts=$((attempts + 1))
    if [ $attempts -ge 3 ]; then
      echo "FAILED image $num after 3 attempts"
      return
    fi
    echo "Retrying image $num (attempt $attempts)..."
    sleep 5
  done
  echo "Done $num"
}

BATCH_SIZE=10
pids=()

run_batch() {
  for pid in "${pids[@]}"; do
    wait "$pid"
  done
  pids=()
}

declare -A PROMPTS

PROMPTS[1]="A stick figure looking up at a deep blue glowing planet in a dark starry sky. Distance label 63 LIGHT YEARS in wobbly handwriting with red arrow."
PROMPTS[2]="The deep blue planet slowly spinning in space with motion lines. Stars surrounding it. Label IT EXISTS RIGHT NOW in wobbly letters."
PROMPTS[3]="The blue planet with SPINNING written in wobbly letters and a spiral arrow around it. Stars in background."
PROMPTS[4]="The blue planet with WAITING written below it in large wobbly letters. Eerie dark space background."
PROMPTS[5]="A stick figure with a massive question mark above their head. Blue planet in background. Label YOU WILL NEVER IMAGINE with red arrow."
PROMPTS[6]="The blue planet from a distance looking calm and beautiful. Label FROM A DISTANCE in wobbly handwriting."
PROMPTS[7]="DEEP BLUE written in large wobbly letters. The glowing blue planet next to it. Stars around it."
PROMPTS[8]="Side by side drawing. Earth on left labelled EARTH. HD 189733b on right labelled THIS. Both blue. Question mark between them. ALMOST LIKE EARTH label."
PROMPTS[9]="A stick figure astronaut zooming toward the blue planet with speed lines. Speech bubble saying COULD SOMETHING LIVE THERE? Shocked expression."
PROMPTS[10]="Stick figure getting close to planet with massive wide eyes and open mouth. Label YOU WOULD NOT BELIEVE IT in red wobbly letters."
PROMPTS[11]="The blue planet with HD 189733b written in large wobbly letters next to it. Red arrow pointing at it."
PROMPTS[12]="The planet surrounded by red lightning bolts explosion symbols and danger signs. Label MOST VIOLENT PLACE EVER DISCOVERED in red handwriting."
PROMPTS[13]="The blue planet with a red X through it and label THE FIRST LIE in wobbly letters. Red arrow pointing at the blue colour."
PROMPTS[14]="Planet surface with X through an ocean drawing and X through a river drawing. NO OCEANS NO RIVERS label in red."
PROMPTS[15]="Planet with NO RAIN written in big letters and X through rain drops. Cross through water droplets."
PROMPTS[16]="Atmosphere layer around planet with tiny glass shards drawn inside it. Label SILICATE PARTICLES in wobbly handwriting. Red arrow pointing to shards."
PROMPTS[17]="TINY FRAGMENTS OF GLASS written in large wobbly letters. Small jagged glass shards around the text. Sparkly dangerous look."
PROMPTS[18]="Planet completely wrapped in a jagged cloud layer made of glass. GLASS EVERYWHERE label. Arrows pointing in every direction."
PROMPTS[19]="A stick figure astronaut surrounded by glass shards coming from above, sides and all around. Arrows pointing at them from every direction. ABOVE YOU AROUND YOU label."
PROMPTS[20]="Split image. Left side: beautiful peaceful blue planet labelled PARADISE FROM OUTSIDE. Right side: red hellish surface labelled CLOSEST THING TO HELL. Red arrow between them."
PROMPTS[21]="Massive wind arrows sweeping horizontally across the planet. 8700 KM/H written in huge wobbly red letters. Speed lines everywhere."
PROMPTS[22]="8700 written in absolutely massive wobbly letters filling the frame. KM PER HOUR below it in red. Exclamation marks."
PROMPTS[23]="Two bars side by side. Short bar labelled EARTH 408 KM/H. Massive tall bar labelled HD189733b 8700 KM/H. Stick figure looking tiny next to the tall bar."
PROMPTS[24]="A wobbly spiral hurricane destroying simple stick figure houses. CATEGORY 5 label. Houses flying away. Stick figures running."
PROMPTS[25]="Stick figure town being completely blown away by wind. ENTIRE TOWNS label. ENTIRE COASTLINES label. GONE written in red."
PROMPTS[26]="21x written in massive wobbly red letters. Wind speed arrows underneath. 21 TIMES FASTER label with red underline."
PROMPTS[27]="Big question mark in centre. Glass shards with speed lines flying sideways around it. WHAT HAPPENS WHEN GLASS TRAVELS AT 8700 KM/H label in wobbly handwriting."
PROMPTS[28]="Thousands of tiny jagged shards flying horizontally across the frame. HURLED SIDEWAYS label. Speed lines showing extreme velocity."
PROMPTS[29]="A speed meter showing 2.5 KM PER SECOND. Red needle in extreme zone. Shock lines around the meter. TWO AND A HALF KM PER SECOND label."
PROMPTS[30]="Rain arrows pointing SIDEWAYS instead of down. Big red circle around the sideways arrows. IT RAINS SIDEWAYS label in huge red letters."
PROMPTS[31]="Three words stacked: GLASS. SIDEWAYS. FOREVER. Each with a red arrow. Speed lines on GLASS. Clock on FOREVER. Sideways arrow on SIDEWAYS."
PROMPTS[32]="Stick figure pointing back at a giant glass shard. Speech bubble saying BUT ABOUT THAT GLASS. Curious expression."
PROMPTS[33]="Simple flat window drawing labelled WHAT PEOPLE PICTURE. Then red X through it. HARMLESS label crossed out."
PROMPTS[34]="Side by side. Left: smooth flat window. Right: jagged irregular sharp crystal shards. NOTHING LIKE THIS label with red arrow."
PROMPTS[35]="Closeup of jagged irregular crystal shards under a magnifying glass. JAGGED label. IRREGULAR label. SHARP EDGES label. All in wobbly handwriting."
PROMPTS[36]="Stick figure coughing with wavy lines coming from mouth. Simple lung drawing with danger symbol. SERIOUS LUNG DISEASE label."
PROMPTS[37]="Stick figure construction worker with hard hat and face mask. EVEN MICROSCOPIC AMOUNTS label. Warning symbols around."
PROMPTS[38]="Planet completely filled and saturated with glass shards. ENTIRE ATMOSPHERE label. Overwhelming amount of shards shown. Red arrows everywhere."
PROMPTS[39]="Single glass shard with bullet speed lines behind it. Equals sign. Bullet drawing. FORCE OF A BULLET label in red wobbly letters."
PROMPTS[40]="Stick figure surrounded by billions of bullet-speed shards flying from every direction. BILLIONS OF THEM label. EVERY SECOND. FROM EVERY DIRECTION labels."
PROMPTS[41]="Stick figure standing on planet surface. Red X next to label NOT CUT. Label SOMETHING WORSE in red arrow."
PROMPTS[42]="Stick figure being sandblasted and disappearing into nothing. SANDBLASTED OUT OF EXISTENCE label. Before and after showing figure then empty space."
PROMPTS[43]="INSTANTLY written in huge letters. GONE below it. Empty space where stick figure was. Just empty space remaining."
PROMPTS[44]="Completely empty space. Wind arrow sweeping away even dust particles. NOTHING LEFT label. NOT EVEN DUST label with red arrow."
PROMPTS[45]="Stick figure with raised finger and knowing expression. Label BUT THERES MORE in wobbly letters. Planet in background."
PROMPTS[46]="Planet shown very close to its blazing star. Red arrow showing tiny distance. WHERE IT SITS label. Star much bigger than planet."
PROMPTS[47]="Tiny circular orbit very close to blazing star. Label 2.2 DAYS = 1 YEAR in wobbly handwriting. Comparison to Earth orbit shown as massive circle far away."
PROMPTS[48]="Calendar with only 2 days on it. Label ONE FULL YEAR. Stick figure with mind blown expression. Exploding head symbol."
PROMPTS[49]="Planet shown having moved along tiny orbit path. Arrow showing movement. ALREADY MOVED label. WHILE YOU WATCHED THIS label."
PROMPTS[50]="Planet with one face always pointing toward blazing star. Padlock symbol. LOCKED IN PLACE label. FOREVER label in red."
PROMPTS[51]="Earth and Moon diagram showing Moon always showing same face. TIDAL LOCKING label. Same thing shown with planet and star below it."
PROMPTS[52]="Planet locked to massive blazing star vs gentle Moon and Earth comparison. SOFT MOONLIGHT crossed out. BLAZING STAR INTENSITY shown with red lines."
PROMPTS[53]="Dayside of planet blasted by full star intensity. Rays hitting it hard. EVERY SECOND label. BILLIONS OF YEARS label. Red heat lines."
PROMPTS[54]="Thermometer at 1000 degrees Celsius. Iron object melting below it. HOT ENOUGH TO MELT IRON label in red wobbly letters."
PROMPTS[55]="Metal objects vaporising into steam and smoke. VAPORISED label. MOST METALS KNOWN TO SCIENCE label. Shocked stick figure watching."
PROMPTS[56]="Dark nightside with thermometer showing 740 degrees Celsius. THE COOL SIDE label with sarcastic arrow. RELATIVELY SPEAKING in small wobbly letters below."
PROMPTS[57]="RELATIVELY SPEAKING written in wobbly letters. Stick figure shrugging. 740 degrees shown. Sarcastic expression."
PROMPTS[58]="Wind arrows with giant question mark above them. WHAT CREATES A WIND THAT NEVER STOPS label. Stick figure looking puzzled."
PROMPTS[59]="Hot side and cold side of planet with gap between them. Temperature gradient shown. TEMPERATURE GAP label with red arrow between the two sides."
PROMPTS[60]="Gas expanding on hot side with sideways arrows showing it has nowhere to go but sideways. EXPANDS label. NOWHERE TO GO BUT SIDEWAYS label."
PROMPTS[61]="Gas rushing from hot side to cold side of planet. Big speed arrows. RUSHES TOWARD NIGHTSIDE label. Extreme speed lines."
PROMPTS[62]="Nightside warming slightly from incoming gas. Pressure arrows shifting direction. PRESSURE SHIFTS label. Back and forth arrows."
PROMPTS[63]="Gas pushing back and forth between two sides. OVER AND OVER label. FOREVER label. Repeating arrows showing endless cycle."
PROMPTS[64]="Massive hurricane spiral covering entire planet. PERMANENT label in red. NEVER PAUSED label. Bold swirling lines."
PROMPTS[65]="Long timeline arrow going far back. BILLIONS OF YEARS AGO label at the far end. Storm symbol at the start of timeline."
PROMPTS[66]="Baby sun still forming shown as swirling gas cloud. BEFORE OUR SUN EXISTED label. Storm already raging nearby."
PROMPTS[67]="Empty space where Earth would be. BEFORE EARTH EXISTED label. Just stars. Dark empty space."
PROMPTS[68]="Dark empty ocean with nothing living in it. BEFORE LIFE label. Empty and dark. Storm symbol in corner showing it was already happening."
PROMPTS[69]="Storm swirl with ALREADY RAGING label. Arrow pointing far back in time. Timeline showing billions of years."
PROMPTS[70]="Stick figures fading and disappearing. Storm continuing behind them. LONG AFTER WE ARE GONE label. Ghostly stick figures."
PROMPTS[71]="Cities and civilisations crossed out with red X. EVERY CIVILISATION label. EVERY CITY label. EVERY MEMORY label. All crossed out. GONE in red."
PROMPTS[72]="Planet still spinning with STILL THERE label. Glass still raining sideways. Storm arrows. STILL RAINING GLASS SIDEWAYS label. 8700 KM/H reminder."
PROMPTS[73]="Stick figure with raised finger and serious expression. THE DETAIL THAT CHANGES EVERYTHING label in large wobbly letters."
PROMPTS[74]="Label MOST PEOPLE NEVER HEAR THIS with red arrow pointing to blank space. Mystery feel. Dark background."
PROMPTS[75]="Telescope with big red X through it. NEVER SEEN DIRECTLY label. Planet in background blurry and unclear."
PROMPTS[76]="Camera with X through it. NOT ONE PHOTOGRAPH label. Emphasised with red underline. NOT ONE in huge letters."
PROMPTS[77]="Scientists with magnifying glass studying a light spectrum beam. ANALYSING STARLIGHT label. Colourful spectrum shown."
PROMPTS[78]="Planet transiting in front of star. Tiny dip in brightness shown. BLOCKS TINY FRACTION OF LIGHT label. Simple diagram."
PROMPTS[79]="Light spectrum with some wavelengths blocked and some passing through. ABSORBED vs NOT ABSORBED label. Scientists studying the difference."
PROMPTS[80]="Single shadow shape on dark background. THATS ALL WE HAVE label. A SHADOW label in large stark wobbly letters."
PROMPTS[81]="Tiny star with barely visible dimming. 63 LIGHT YEARS label. Tiny dip shown. TINY DIMMING label with red arrow."
PROMPTS[82]="Shadow shape on left connected by arrow to detailed terrifying planet on right. FROM THIS label pointing at shadow. TO THIS label pointing at planet."
PROMPTS[83]="Stick figure sitting with chin in hand thinking deeply. Giant thought bubble above. THINK ABOUT WHAT THAT MEANS label."
PROMPTS[84]="Rocket ship with red X through it. NEVER VISITED label in big wobbly letters. Empty space around it."
PROMPTS[85]="Space probe with red X through it. NEVER SENT ANYTHING label. Just empty space."
PROMPTS[86]="Blurry unclear planet image. CANNOT SEE IT CLEARLY label. Question marks around the blurry image."
PROMPTS[87]="Glass raining sideways with speed lines. AND YET WE KNOW label in bold wobbly letters. Contradiction shown visually."
PROMPTS[88]="Stick figure vaporising before reaching planet surface. BEFORE YOU LANDED label. Disappearing before touching down."
PROMPTS[89]="Wind erasing stick figure completely. ERASED BEFORE THE HEAT label. Figure disappearing into nothing from wind alone."
PROMPTS[90]="Tiny shadow crossing a distant star. 63 LIGHT YEARS AWAY label. ALL FROM THIS label with red arrow pointing at shadow."
PROMPTS[91]="Stick figure with glowing brain and stars around head. HUMAN CURIOSITY AT ITS MOST EXTRAORDINARY label. Awe expression."
PROMPTS[92]="Three panels in a row each with red X. CANNOT GO. CANNOT SEND. CANNOT SEE. Three separate X panels."
PROMPTS[93]="Stick figure with arms crossed and determined expression. WE REFUSED TO ACCEPT NOT KNOWING label. Stubborn pose."
PROMPTS[94]="Stick figure studying a beam of light with tools. WE STUDIED THE LIGHT label. Focused expression. Light spectrum shown."
PROMPTS[95]="Complex scientific instrument drawing with many parts. SENSITIVE ENOUGH TO DETECT label. DIFFERENCE BETWEEN WAVELENGTHS label."
PROMPTS[96]="Puzzle pieces coming together to form a planet shape. RECONSTRUCTED label. Pieces clicking into place. AN ENTIRE ALIEN WORLD label."
PROMPTS[97]="Terrifying nightmare planet with all its features shown. IN EXTRAORDINARY DETAIL label. Red arrows pointing to each feature."
PROMPTS[98]="Scientist lying awake in bed with wide open eyes. Planet thoughts in thought bubble above. KEEPS SCIENTISTS UP AT NIGHT label."
PROMPTS[99]="Shadow with enormous question mark above it. IF WE KNOW ALL THIS FROM A SHADOW label. Dramatic presentation."
PROMPTS[100]="Vast dark space filled with hundreds of unexplored planet shapes. WHAT ELSE IS OUT THERE label. Overwhelming number of unknowns."
PROMPTS[101]="Long list scrolling down with planet names. THOUSANDS label in large letters. CONFIRMED BUT NEVER STUDIED label."
PROMPTS[102]="Thousands of shadow shapes. THOUSANDS OF SHADOWS label. HAVENT ANALYSED label. Dark mysterious feel."
PROMPTS[103]="Rows and rows of blank unnamed planet shapes. THOUSANDS OF WORLDS label. UNDESCRIBED label. Vast number shown."
PROMPTS[104]="Planet with WORSE? label and shocked stick figure next to it. Could be worse than HD 189733b shown with question mark."
PROMPTS[105]="Strange alien planet with question marks all around it. NO WORDS FOR IT label. STRANGER THAN LANGUAGE label. Bizarre shapes."
PROMPTS[106]="Space filled with many different dangerous planets. NOT EMPTY label in big letters. FULL OF PLACES LIKE THIS label."
PROMPTS[107]="Earth glowing gently and warmly. IMPOSSIBLY GENTLE label. IMPOSSIBLY PERFECT label. Soft warm glow compared to harsh planets."
PROMPTS[108]="Tiny Earth dot in vast dark space. PALE BLUE DOT label. Very small Earth surrounded by enormous emptiness."
PROMPTS[109]="Tiny Earth floating among terrifying harsh planets. FLOATING IN CHAOS label. Earth looks fragile and small."
PROMPTS[110]="Stick figure with lucky stars and four leaf clovers around them. WE GOT LUCKY label. INCREDIBLY LUCKY label. Lucky symbols everywhere."
PROMPTS[111]="Billions of harsh dangerous planets shown. THEY DIDNT GET LUCKY label. Contrast with lucky Earth."
PROMPTS[112]="Earth glowing warmly with RARE label. HOW RARE THIS PLACE IS label. Warm golden glow around Earth. Stars in background."

declare -A TIMESTAMPS
TIMESTAMPS[1]="ends_0m05s0"
TIMESTAMPS[2]="ends_0m10s0"
TIMESTAMPS[3]="ends_0m15s0"
TIMESTAMPS[4]="ends_0m20s0"
TIMESTAMPS[5]="ends_0m25s0"
TIMESTAMPS[6]="ends_0m30s0"
TIMESTAMPS[7]="ends_0m35s0"
TIMESTAMPS[8]="ends_0m40s0"
TIMESTAMPS[9]="ends_0m45s0"
TIMESTAMPS[10]="ends_0m50s0"
TIMESTAMPS[11]="ends_0m55s0"
TIMESTAMPS[12]="ends_1m00s0"
TIMESTAMPS[13]="ends_1m05s0"
TIMESTAMPS[14]="ends_1m10s0"
TIMESTAMPS[15]="ends_1m15s0"
TIMESTAMPS[16]="ends_1m20s0"
TIMESTAMPS[17]="ends_1m25s0"
TIMESTAMPS[18]="ends_1m30s0"
TIMESTAMPS[19]="ends_1m35s0"
TIMESTAMPS[20]="ends_1m40s0"
TIMESTAMPS[21]="ends_1m45s0"
TIMESTAMPS[22]="ends_1m50s0"
TIMESTAMPS[23]="ends_1m55s0"
TIMESTAMPS[24]="ends_2m00s0"
TIMESTAMPS[25]="ends_2m05s0"
TIMESTAMPS[26]="ends_2m10s0"
TIMESTAMPS[27]="ends_2m15s0"
TIMESTAMPS[28]="ends_2m20s0"
TIMESTAMPS[29]="ends_2m25s0"
TIMESTAMPS[30]="ends_2m30s0"
TIMESTAMPS[31]="ends_2m35s0"
TIMESTAMPS[32]="ends_2m40s0"
TIMESTAMPS[33]="ends_2m45s0"
TIMESTAMPS[34]="ends_2m49s0"
TIMESTAMPS[35]="ends_2m54s0"
TIMESTAMPS[36]="ends_2m59s0"
TIMESTAMPS[37]="ends_3m04s0"
TIMESTAMPS[38]="ends_3m09s0"
TIMESTAMPS[39]="ends_3m14s0"
TIMESTAMPS[40]="ends_3m19s0"
TIMESTAMPS[41]="ends_3m24s0"
TIMESTAMPS[42]="ends_3m29s0"
TIMESTAMPS[43]="ends_3m34s0"
TIMESTAMPS[44]="ends_3m39s0"
TIMESTAMPS[45]="ends_3m44s0"
TIMESTAMPS[46]="ends_3m49s0"
TIMESTAMPS[47]="ends_3m54s0"
TIMESTAMPS[48]="ends_3m59s0"
TIMESTAMPS[49]="ends_4m04s0"
TIMESTAMPS[50]="ends_4m09s0"
TIMESTAMPS[51]="ends_4m14s0"
TIMESTAMPS[52]="ends_4m19s0"
TIMESTAMPS[53]="ends_4m23s0"
TIMESTAMPS[54]="ends_4m28s0"
TIMESTAMPS[55]="ends_4m33s0"
TIMESTAMPS[56]="ends_4m38s0"
TIMESTAMPS[57]="ends_4m43s0"
TIMESTAMPS[58]="ends_4m48s0"
TIMESTAMPS[59]="ends_4m53s0"
TIMESTAMPS[60]="ends_4m58s0"
TIMESTAMPS[61]="ends_5m03s0"
TIMESTAMPS[62]="ends_5m08s0"
TIMESTAMPS[63]="ends_5m13s0"
TIMESTAMPS[64]="ends_5m18s0"
TIMESTAMPS[65]="ends_5m23s0"
TIMESTAMPS[66]="ends_5m28s0"
TIMESTAMPS[67]="ends_5m33s0"
TIMESTAMPS[68]="ends_5m38s0"
TIMESTAMPS[69]="ends_5m43s0"
TIMESTAMPS[70]="ends_5m48s0"
TIMESTAMPS[71]="ends_5m53s0"
TIMESTAMPS[72]="ends_5m58s0"
TIMESTAMPS[73]="ends_6m03s0"
TIMESTAMPS[74]="ends_6m08s0"
TIMESTAMPS[75]="ends_6m13s0"
TIMESTAMPS[76]="ends_6m18s0"
TIMESTAMPS[77]="ends_6m23s0"
TIMESTAMPS[78]="ends_6m28s0"
TIMESTAMPS[79]="ends_6m33s0"
TIMESTAMPS[80]="ends_6m38s0"
TIMESTAMPS[81]="ends_6m43s0"
TIMESTAMPS[82]="ends_6m48s0"
TIMESTAMPS[83]="ends_6m53s0"
TIMESTAMPS[84]="ends_6m58s0"
TIMESTAMPS[85]="ends_7m03s0"
TIMESTAMPS[86]="ends_7m08s0"
TIMESTAMPS[87]="ends_7m13s0"
TIMESTAMPS[88]="ends_7m18s0"
TIMESTAMPS[89]="ends_7m23s0"
TIMESTAMPS[90]="ends_7m28s0"
TIMESTAMPS[91]="ends_7m33s0"
TIMESTAMPS[92]="ends_7m38s0"
TIMESTAMPS[93]="ends_7m43s0"
TIMESTAMPS[94]="ends_7m48s0"
TIMESTAMPS[95]="ends_7m53s0"
TIMESTAMPS[96]="ends_7m58s0"
TIMESTAMPS[97]="ends_8m03s0"
TIMESTAMPS[98]="ends_8m08s0"
TIMESTAMPS[99]="ends_8m13s0"
TIMESTAMPS[100]="ends_8m18s0"
TIMESTAMPS[101]="ends_8m23s0"
TIMESTAMPS[102]="ends_8m28s0"
TIMESTAMPS[103]="ends_8m33s0"
TIMESTAMPS[104]="ends_8m38s0"
TIMESTAMPS[105]="ends_8m43s0"
TIMESTAMPS[106]="ends_8m48s0"
TIMESTAMPS[107]="ends_8m53s0"
TIMESTAMPS[108]="ends_8m58s0"
TIMESTAMPS[109]="ends_9m03s0"
TIMESTAMPS[110]="ends_9m08s0"
TIMESTAMPS[111]="ends_9m13s0"
TIMESTAMPS[112]="ends_9m19s0"

count=0
for i in $(seq 1 112); do
  gen "$i" "${PROMPTS[$i]}" &
  pids+=($!)
  count=$((count + 1))
  if [ $count -eq $BATCH_SIZE ]; then
    run_batch
    count=0
  fi
done
run_batch

echo ""
echo "All 112 images generated! Check the output_glass/ folder."
