#!/bin/bash

HF=/opt/homebrew/lib/node_modules/@higgsfield/cli/vendor/hf
STYLE="Stick figure illustration rich vibrant colours. Thick uneven black outlines. Wobbly hand drawn lines. Stick figure humans with round heads dot eyes simple line bodies. Rich vibrant colourful backgrounds. Mars scenes deep red and orange backgrounds with rust red ground and pink sky. Handwritten labels and red arrows for emphasis. Objects simple but clearly recognisable. Lots of colour bright yellows electric blues vivid purples warm oranges glowing greens. Every scene feels alive with colour and energy. No realistic shading no 3D no white backgrounds. 16:9 aspect ratio."

mkdir -p output_mars

gen() {
  local num=$1
  local prompt=$2
  if grep -q "https://" "output_mars/image_${num}.txt" 2>/dev/null; then
    echo "Skipping image $num (already done)"
    return
  fi
  local attempts=0
  echo "Generating image $num..."
  local job_id=""
  until [[ -n "$job_id" ]]; do
    job_id=$($HF generate create nano_banana_2 --prompt "${STYLE} ${prompt}" --json 2>/dev/null | tr -d '[]" \n')
    if [[ -z "$job_id" ]]; then
      attempts=$((attempts + 1))
      if [ $attempts -ge 3 ]; then
        echo "FAILED image $num after 3 attempts"
        return
      fi
      echo "Retrying image $num (attempt $attempts)..."
      sleep 5
    fi
  done
  echo "Waiting for image $num..."
  $HF generate wait "$job_id" > "output_mars/image_${num}.txt" 2>&1
  echo "Done $num"
}

BATCH_SIZE=10
pids=()

run_batch() {
  for pid in "${pids[@]}"; do
    wait "$pid"
  done
  pids=()
}

declare -A PROMPTS

PROMPTS[1]="6AM label bold on alarm clock. Stick figure waking up in bed eyes opening. Alarm going off. Dark bedroom. First moment of waking. YOUR ALARM GOES OFF label."
PROMPTS[2]="Stick figure opening eyes wide. NOT A CEILING label bold. Dome window visible above them. Rust red Mars sky outside. Shocked realisation expression."
PROMPTS[3]="RUST RED SKY label bold. Reinforced dome window with bolts around edge. Mars landscape outside. Pink orange sky. Stick figure staring through it. YOU ARE NOT ON EARTH feeling."
PROMPTS[4]="YOU ARE NOT ON EARTH label enormous bold red letters filling frame. Mars surface visible below. Stick figure small against the vast red landscape. Powerful stark image."
PROMPTS[5]="225 MILLION KILOMETRES label enormous. Earth tiny pale blue dot far away in space. Stick figure arms wide apart showing distance. EVERYONE YOU HAVE EVER LOVED label with arrow pointing at Earth dot."
PROMPTS[6]="AND TODAY IS JUST ANOTHER TUESDAY label bold. Calendar on wall showing Tuesday. Stick figure shrugging casually. Mars dome window behind them. Mundane routine feel."
PROMPTS[7]="DAILY LIFE ON MARS 2055 label bold centre frame. Mars colony domes on rust red surface. Stick figures going about daily tasks. Futuristic but ordinary routine feel."
PROMPTS[8]="NOTHING LIKE WHAT YOU IMAGINED label bold. Stick figure with shocked disappointed expression. Thought bubble showing imagined glamorous Mars vs dull reality. Contrast shown."
PROMPTS[9]="SUBSCRIBE TO UNKNOWN ORIGINS label bold. Big glowing subscribe button. Stars and planets background. Stick figure pressing button eagerly. Unknown Origins channel feel."
PROMPTS[10]="STRANGEST MYSTERIES label. Space scene on top ocean scene on bottom. Telescope pointing at stars. OUTER SPACE AND DEEP OCEAN label. EVERY WEEK label bold."
PROMPTS[11]="YOU DO NOT WANT TO MISS WHAT IS COMING label bold dramatic. Exciting space background. Mysterious silhouettes of future videos. Dramatic teaser feel. Stars everywhere."
PROMPTS[12]="LET'S START WITH HOW YOU GOT THERE label. Rocket launching from Earth leaving trail of fire. THE JOURNEY label bold. Earth getting smaller behind rocket."
PROMPTS[13]="THE JOURNEY ALONE IS ENOUGH TO CHANGE YOU FOREVER label. Stick figure entering rocket one person and exiting Mars a different person. Before and after transformation shown."
PROMPTS[14]="7 TO 9 MONTHS label enormous bold. Earth on left Mars on right. Long dotted arrow between them. TRIP FROM EARTH TO MARS label. Vast empty space in between."
PROMPTS[15]="NINE MONTHS label bold. Spacecraft shown same size as large house with size comparison. Stick figures visible through windows. ROUGHLY THE SIZE OF A LARGE HOUSE label."
PROMPTS[16]="SAME SIX TO EIGHT PEOPLE label. Six stick figures crammed in small spacecraft interior. EVERY SINGLE DAY label bold. Repetition arrows. Same faces same space every day."
PROMPTS[17]="NO FRESH AIR label crossed out. NO OPEN SPACES label crossed out. NO PRIVACY label crossed out. Three panels each with red X. Stick figures cramped and uncomfortable."
PROMPTS[18]="THIRD QUARTER PHENOMENON label bold dramatic. Psychologist stick figure with clipboard. WHAT HAPPENS TO ASTRONAUTS ON LONG MISSIONS label. Scientific diagram of mental state."
PROMPTS[19]="HALFWAY THROUGH label on timeline. Brain diagram splitting from EXCITED on left to TRAPPED on right. STOPS FEELING EXCITED label. STARTS FEELING TRAPPED label. Dramatic change shown."
PROMPTS[20]="MOTIVATION DROPS label with big downward arrow. MOOD DETERIORATES label. ARGUMENTS BREAK OUT label. Three stick figures upset and disagreeing in cramped spacecraft."
PROMPTS[21]="STILL HAVE MONTHS LEFT TO GO label. Timeline showing enormous remaining distance. Exhausted stick figure slumped. Calendar with many days remaining crossed off slowly."
PROMPTS[22]="ALREADY A DIFFERENT PERSON label bold. Before stick figure on left smiling when leaving Earth. After stick figure on right changed expression arriving at Mars. WHEN YOU LEFT vs NOW label."
PROMPTS[23]="LANDING ON MARS NOT LIKE LANDING ON EARTH label bold. Two planet comparison side by side. Normal Earth landing crossed out. Strange Mars landing shown. Very different label."
PROMPTS[24]="ATMOSPHERE JUST 1 PERCENT OF EARTH'S label. Thin wisp of atmosphere around Mars vs thick layer around Earth. PARACHUTES BARELY WORK label. Parachute barely slowing tiny spacecraft."
PROMPTS[25]="ROCKET BRAKING SYSTEMS label bold. Rockets firing downward below spacecraft. LAST POSSIBLE SECOND label dramatic. Flames slowing descent just in time. Tense dramatic scene."
PROMPTS[26]="IF ANYTHING GOES WRONG label bold red. NO RESCUE MISSION COMING label enormous. Red X through rescue rocket trying to launch. Alone. Isolated. No help possible."
PROMPTS[27]="NEAREST HELP label. 7 MONTH JOURNEY AWAY label bold. Earth tiny dot in distance. Enormous arrow showing distance. Stick figure alone on Mars. Complete isolation shown."
PROMPTS[28]="YOU LAND label dramatic bold. Airlock door opening for first time. Boots touching Mars rust red soil. FIRST TIME YOU STEP OUTSIDE label. Historic moment. Footprint shown."
PROMPTS[29]="THE SKY IS NOT BLUE label with red X through blue. PALE BUTTERSCOTCH PINK label bold. Mars pink orange sky shown vividly. Stick figure looking up in surprise at wrong colour sky."
PROMPTS[30]="SUNRISE AND SUNSET IT TURNS BLUE label. THE EXACT OPPOSITE OF EARTH label bold. Split image Earth blue day sky vs Mars blue only at sunrise sunset. Opposite shown clearly."
PROMPTS[31]="IRON OXIDE label. RUST label enormous bold red. Ground stretching to horizon all deep rust red orange. AS FAR AS YOU CAN SEE IN EVERY DIRECTION label. Vast empty red landscape."
PROMPTS[32]="NO TREES label crossed out. NO GRASS label crossed out. NO WATER label crossed out. NO SOUND label crossed out. Four panels completely empty. Stark absence of life shown."
PROMPTS[33]="ALMOST COMPLETELY SILENT label enormous bold filling frame. Empty Mars landscape. Sound wave symbols crossed out. Stick figure in total silence. Profound emptiness shown."
PROMPTS[34]="TOO THIN TO CARRY SOUND label. Atmosphere diagram showing very thin layer. Sound waves starting then fading into nothing. ATMOSPHERE label. Science diagram style."
PROMPTS[35]="A ROCK SLIDE A KILOMETRE AWAY WOULD BE INAUDIBLE label. Rockslide happening in background. Stick figure in foreground hearing absolutely nothing. INAUDIBLE label. Silence."
PROMPTS[36]="QUIETEST PLACE ANY HUMAN HAS EVER STOOD label bold dramatic. Stick figure standing completely alone on vast Mars plain. Total silence. Historic label. Profound moment."
PROMPTS[37]="CANNOT STAY OUTSIDE FOR LONG label bold red. Suit timer counting down. Warning symbols. Clock ticking. Danger reminder. Limited time outside shown urgently."
PROMPTS[38]="MINUS 73 DEGREES AT NIGHT label in blue cold colours. JUST ABOVE ZERO DURING THE DAY label. Temperature swing thermometer shown dramatically. Extreme range label."
PROMPTS[39]="95 PERCENT CARBON DIOXIDE label bold. Atmosphere pie chart almost entirely CO2. Danger symbol. Toxic atmosphere warning. Tiny sliver of other gases shown. CO2 dominates."
PROMPTS[40]="WITHOUT YOUR SUIT label with dramatic red X. LOSE CONSCIOUSNESS IN SECONDS label. DEAD IN MINUTES label. Stick figure without suit shown in danger. Suit is survival shown."
PROMPTS[41]="YOUR HOME IS UNDERGROUND label. Cross section diagram showing underground habitat. Tunnels and rooms below Mars surface. Stick figure living below ground. Underground life."
PROMPTS[42]="PRESSURISED DOMES ON THE SURFACE label. Transparent dome on Mars surface. Stick figures visible inside. Rust red landscape outside. Safe bubble of atmosphere inside dome."
PROMPTS[43]="MATERIALS SHIPPED FROM EARTH label. Rockets bringing supplies and building materials. MARTIAN ROCK ITSELF label. Construction shown. Building habitat from local and imported materials."
PROMPTS[44]="1000 PEOPLE label enormous bold. BY 2055 label. Mars map showing settlement locations. Stick figures dotted across colony. Small but growing human presence on Mars."
PROMPTS[45]="SEVERAL CONNECTED HABITAT MODULES label. Diagram of domes connected by underground tunnels. Network of living spaces. Colony layout shown from above. Connected community."
PROMPTS[46]="SIZE OF A LARGE APARTMENT BLOCK label. Each module with size comparison arrow. Tall apartment block shown next to habitat module. Stick figure for scale reference."
PROMPTS[47]="EVERY CUBIC METRE EXPENSIVE label. Price tag attached to small room. EXPENSIVE TO BUILD label. EXPENSIVE TO MAINTAIN label. Cost shown dramatically. Space is precious."
PROMPTS[48]="PERSONAL SPACE IS TINY label enormous ironic. Stick figure barely fitting in small room. Arms touching both walls. TINY label. Claustrophobic feeling. Very small living space."
PROMPTS[49]="ROOM THE SIZE OF A WALK-IN WARDROBE label. Tiny room with single bed shelf and nothing else. THAT IS YOUR HOME label bold. Stick figure in their complete tiny world."
PROMPTS[50]="YOUR DAY STARTS WITH EXERCISE label. NOT BECAUSE YOU WANT TO label crossed arms reluctant stick figure. BECAUSE YOU HAVE TO label bold underlined. Exercise as medical necessity."
PROMPTS[51]="MARS GRAVITY 38 PERCENT OF EARTH'S label bold. Gravity comparison diagram. Stick figure jumping higher on Mars. 38% label large. Lower gravity shown with floating feel."
PROMPTS[52]="MUSCLES AND BONES CONSTANTLY LOSING DENSITY label. Skeleton diagram showing bone density decreasing. Muscle shrinking arrows. Body slowly weakening without exercise."
PROMPTS[53]="TWO HOURS OF EXERCISE EVERY SINGLE DAY label bold. Clock showing 2 hours highlighted. Stick figure on treadmill. EVERY DAY label repeated. No days off. Medical requirement."
PROMPTS[54]="PHYSICALLY UNABLE TO RETURN TO EARTH label dramatic bold. Stick figure collapsed under heavy Earth gravity shown in thought bubble. Body unable to cope. Serious consequence."
PROMPTS[55]="THE THING NOBODY TALKS ABOUT label bold dramatic red. Stick figure leaning in with serious expression. Secret reveal moment. Dramatic pause. Important revelation coming."
PROMPTS[56]="BODY ADAPTS COMPLETELY label. Stick figure gradually changing to Mars physiology. RETURNING TO EARTH BECOMES IMPOSSIBLE label bold. Point of no return concept shown."
PROMPTS[57]="THE GRAVITY WOULD CRUSH YOU label. YOUR HEART WOULDN'T COPE label. Stick figure struggling under Earth gravity weight pressing down. Crushed by returning home. Tragic."
PROMPTS[58]="SOME OF THE FIRST MARTIANS MAY NEVER COME HOME label enormous bold dramatic. Stick figure on Mars looking at Earth tiny dot. NEVER COME HOME label. Permanent exile shown."
PROMPTS[59]="BREAKFAST IS GROWN ON MARS label. Underground farm glowing with artificial light. Stick figure eating breakfast at table. Mars grown food shown simply. Morning routine."
PROMPTS[60]="ENORMOUS UNDERGROUND GROWING FACILITIES label. Cross section diagram of massive underground farm. Row upon row of plants. Scale shown impressively. Underground agriculture."
PROMPTS[61]="ARTIFICIAL LIGHTS label glowing bright. RUNNING ON NUCLEAR POWER label. Lights shining down on plants underground. Nuclear symbol shown. Power source keeping plants alive."
PROMPTS[62]="POTATOES label with drawing. LEAFY GREENS label with drawing. CERTAIN GRAINS label with drawing. Three simple food items shown. Limited menu. Basic survival food only."
PROMPTS[63]="TOXIC PERCHLORATES label bold warning symbol. MARTIAN SOIL label. Soil treatment process diagram shown. Chemical being removed. Careful preparation before food can grow."
PROMPTS[64]="THE FOOD KEEPS YOU ALIVE label. BUT IT IS NOT WHAT YOU DREAMED OF label. Sad stick figure eating plain meal. Thought bubble showing imagined delicious food vs plain reality."
PROMPTS[65]="NO FRESH FRUIT label red X. NO COFFEE label red X. NO STEAK label red X. Three beloved foods crossed out. Sad stick figure. Things that don't exist on Mars shown clearly."
PROMPTS[66]="SO RARE SAVED FOR SPECIAL OCCASIONS label. Single piece of fruit in glass display case like precious jewel. Spotlight on it. Rare treat label. One day a year feel."
PROMPTS[67]="WATER FROM ICE label. Ice drilling and extraction from below Mars surface. BELOW THE MARTIAN SURFACE label. Mining equipment. Water being extracted from permafrost."
PROMPTS[68]="MELTED FILTERED RECYCLED label three steps shown. EVERY DROP USED MULTIPLE TIMES label. Water cycle diagram. Nothing wasted. Same water going round and round. Precious resource."
PROMPTS[69]="NOTHING IS WASTED label bold. NOTHING CAN BE label. Every resource shown with recycling arrows. All materials reused. Closed loop system. Survival depends on zero waste."
PROMPTS[70]="YOU CAN CALL HOME label. Stick figure at communication screen with hopeful expression. Earth visible tiny in background. Family on screen. Connection across vast space shown."
PROMPTS[71]="3 TO 22 MINUTES TO ARRIVE label bold. Signal beam travelling between Earth and Mars. Different orbit positions shown. Delay varies. DEPENDING ON ORBITS label. Time shown."
PROMPTS[72]="40 MINUTES FOR A SINGLE EXCHANGE label. Conversation timeline diagram. Message sent. 22 minute wait. Reply received. 22 minute wait. Total time shown. Very slow exchange."
PROMPTS[73]="YOU DON'T HAVE CONVERSATIONS label crossed out. YOU SEND MESSAGES label. AND WAIT label. Stick figure typing message then sitting waiting. Clock ticking slowly. Lonely wait."
PROMPTS[74]="AND WAIT label enormous filling frame. Stick figure sitting staring at blank screen. Clock on wall barely moving. Earth in small window. Aching slowness of communication."
PROMPTS[75]="YOUR FAMILY IS AGING WITHOUT YOU label. Family on Earth growing older in time lapse style. Parents with grey hair. Children growing up. Stick figure on Mars missing it all."
PROMPTS[76]="BIRTHDAYS PASS label. FUNERALS HAPPEN label. GRANDCHILDREN ARE BORN label. Three life events shown. All happening without the Mars colonist present. Life continuing without them."
PROMPTS[77]="22 MINUTE DELAY label. 225 MILLION KILOMETRES AWAY label. Watching family events on small screen with delay indicator. Distance visualised. Emotional disconnection shown."
PROMPTS[78]="SOMETHING ELSE LIVING ON MARS DOES TO YOU label dramatic. Ominous tone shift. Dark atmospheric background. Something unknown coming. Stick figure looking uncertain. Warning."
PROMPTS[79]="RADIATION label enormous bold dramatic. Something nobody knows long term effects of yet. Scientists with question marks. Unknown danger. Invisible threat shown with warning symbols."
PROMPTS[80]="EARTH MAGNETIC FIELD label. Shield bubble around Earth deflecting cosmic rays. DEFLECTS THE MOST DANGEROUS COSMIC RAYS label. Earth protected. Safe under the shield shown."
PROMPTS[81]="MARS HAS ALMOST NO MAGNETIC FIELD label bold red. No shield around Mars. Cosmic rays raining down directly onto surface. Unprotected. Exposed. Danger from space shown."
PROMPTS[82]="700 TIMES HIGHER THAN ON EARTH label enormous bold red. Radiation comparison chart. Earth level tiny bar. Mars level enormous bar shooting off the chart. Dramatic difference."
PROMPTS[83]="HUNDREDS OF MEDICAL X-RAYS label. Stack of X-ray images piling up. EVERY YEAR ON MARS label. Radiation accumulating in body shown. Year after year of exposure building up."
PROMPTS[84]="CANCER RISK label warning. NEUROLOGICAL DAMAGE label warning. GENETIC CHANGES label warning. Three serious risks shown. STILL BEING STUDIED label. Unknown outcomes. Concern."
PROMPTS[85]="YOU SIGNED THE WAIVER label. Stick figure signing large document. YOU KNEW THE RISKS label. Waiver paper shown. Agreement made before leaving. Consent given. Now living with it."
PROMPTS[86]="KNOWING A RISK label on left. AND LIVING WITH IT EVERY DAY label on right. TWO VERY DIFFERENT THINGS label bold in middle. Stick figure realising the difference. Daily reality."
PROMPTS[87]="THE HARDEST PART label bold. NOT THE RADIATION label crossed out. NOT THE FOOD label crossed out. NOT EVEN THE DANGER label crossed out. Building to reveal. What is it then."
PROMPTS[88]="IT IS THE SKY label enormous dramatic bold filling most of frame. Simple powerful image. Just those words on rust red background. Emotional peak moment. Pause and breathe."
PROMPTS[89]="RUST RED LANDSCAPE label. Stick figure at window every morning. Same view every single day. NO CHANGE label. Repetition arrows. Same rust red every morning forever. Grinding routine."
PROMPTS[90]="NO GREEN label. NO BLUE SKY label. NO RAIN label. Three absences shown with gentle sadness. Not harsh X marks but faded empty spaces where these things should be. Missing."
PROMPTS[91]="NO WIND YOU CAN FEEL label. NO SMELL OF GRASS label. NO OCEAN label. Three more missing sensory experiences. Stick figure reaching out for things that aren't there. Longing."
PROMPTS[92]="ABSENCE OF NATURE label. PSYCHOLOGICAL DETERIORATION label. Studies and research shown. Scientists measuring mental decline. Graphs showing gradual deterioration over time."
PROMPTS[93]="NATURE DEFICIT label bold clinical. Scientists with clipboards and data. Specific condition named. Graph declining slowly. Clinical term for a deeply human suffering. Label shown."
PROMPTS[94]="IT BUILDS SLOWLY label. LIKE A COLOUR DRAINING FROM THE WORLD label. Colour literally fading from image. World becoming less vivid. Slow invisible damage accumulating."
PROMPTS[95]="DREAMING ABOUT EARTH CONSTANTLY label. Stick figure asleep with Earth dream bubble above. MANY MARTIAN COLONISTS label. Multiple dreamers shown. Common experience among colonists."
PROMPTS[96]="ABOUT RAIN label with raindrops in dream bubble. ABOUT FORESTS label with trees. ABOUT THE SMELL OF THE OCEAN label with waves. Three dream sequences shown in thought bubbles."
PROMPTS[97]="THINGS SO ORDINARY label. NEVER THOUGHT TO APPRECIATE THEM label bold. Simple Earth things shown as suddenly precious. Grass puddle breeze. Ordinary made extraordinary by absence."
PROMPTS[98]="BUT HERE IS WHAT THOSE SAME COLONISTS ALSO SAY label. Tone turning positive. Leaning forward moment. Something unexpected and beautiful coming. Anticipation building."
PROMPTS[99]="CLEAR EVENINGS label. WHEN DUST STORMS SETTLE label. Stick figure walking toward observation dome at night. Stars visible above dome. Special evening. Anticipation shown."
PROMPTS[100]="AND YOU CAN LOOK UP label. Stick figure inside dome looking upward at vast star filled sky. Face tilted up. Wonder expression. The whole universe above them. Awe moment."
PROMPTS[101]="SKY ON MARS AT NIGHT label. NO HUMAN WHO STAYED ON EARTH WILL EVER SEE THIS label bold. Unique view. Something only Martian colonists have ever witnessed. Special exclusive view."
PROMPTS[102]="NO LIGHT POLLUTION label. NO ATMOSPHERE TO BLUR THE STARS label. Crystal clear perfect star field above. Every star sharp and vivid. Clearest view of universe ever seen."
PROMPTS[103]="JUST THE RAW UNIVERSE label. CLOSER AND CLEARER label. THAN ANY HUMAN EYE HAS EVER SEEN IT label. Overwhelming beauty of naked stars. Stick figure overwhelmed by scale."
PROMPTS[104]="IMPOSSIBLE BLACK OCEAN OF LIGHT label. SMALL PALE BLUE DOT label. Stars everywhere. Among them one tiny blue dot with arrow pointing at it. Earth identified. So small. So far."
PROMPTS[105]="SO SMALL YOU COULD COVER IT WITH YOUR THUMB label. Stick figure hand with thumb raised covering the tiny Earth dot in the star field. Scale of distance shown powerfully."
PROMPTS[106]="THAT IS EARTH label bold with arrow. THAT IS EVERYONE YOU HAVE EVER KNOWN label. Earth as tiny dot with tiny stick figures visible on it. All of humanity on one small dot."
PROMPTS[107]="EVERYTHING YOU HAVE EVER LOVED label. COMPRESSED INTO A SINGLE PIXEL OF LIGHT label. Earth reduced to one dot. Everything precious made tiny by distance. Profound realisation."
PROMPTS[108]="IN THAT MOMENT label. EVERY SINGLE ONE OF THEM label. FEELS THE SAME THING label. Multiple colonists at dome together all looking up. Shared experience. Collective feeling."
PROMPTS[109]="NOT HOMESICKNESS label with gentle X. NOT REGRET label with gentle X. Something entirely different. Question mark. What is this new feeling. Building to the answer. Unknown emotion."
PROMPTS[110]="SOMETHING THEY DON'T HAVE WORDS FOR YET label bold. Blank dictionary page with empty space where the word should be. New feeling. No existing language for it. New human experience."
PROMPTS[111]="THE BEGINNING OF WHAT IT MEANS TO BE FROM SOMEWHERE ELSE label. New identity forming. Stick figure transforming. Concept of home changing. New understanding emerging slowly."
PROMPTS[112]="THE FIRST HUMANS WHO ARE NOT FROM EARTH label enormous historic. Stick figures on Mars surface. Milestone in human history shown. Historic label. This moment matters."
PROMPTS[113]="BUT FROM MARS label enormous bold filling frame. Stick figures on Mars surface proud and planted. New home. New identity. MARTIANS label. First generation of true Martians. Powerful."
PROMPTS[114]="SUBSCRIBE TO UNKNOWN ORIGINS label bold large. Channel logo with stars and Mars and Earth. Big glowing subscribe button. Stick figure pressing it. Space background. Call to action."
PROMPTS[115]="EVERY VIDEO IS ANOTHER WORLD label. ANOTHER MYSTERY label. Montage of future video topics shown as small screens. Space and ocean mysteries hinted. Series feel. More coming."
PROMPTS[116]="DROP A COMMENT label bold. WOULD YOU GO TO MARS IF YOU COULD label question in large wobbly letters. Comment box shown. Viewer engagement. Big question to think about. Yes or no."
PROMPTS[117]="WE'LL SEE YOU IN THE NEXT ONE label. Stick figure waving goodbye warmly. Mars surface behind them. Earth visible as dot in sky. Unknown Origins feel. Warm farewell. See you soon."
PROMPTS[118]="Stick figure floating lighter in Mars gravity. Body slowly changing adapting to Mars. Calendar showing months passing. MONTHS PASS label. TIME ON MARS changes you label. Adapting."
PROMPTS[119]="BILLIONS OF STARS label. Stick figure arms wide overwhelmed by night sky beauty on Mars. Stars stretching to every edge of frame. THE RAW UNIVERSE label. Beauty and scale shown."
PROMPTS[120]="Unknown Origins logo centre frame. Mars on one side Earth on other. Stars everywhere. UNKNOWN ORIGINS label bold. SPACE AND OCEAN MYSTERIES label. Final end card. Channel branding."

declare -A TIMESTAMPS
TIMESTAMPS[1]="ends_0m04s"
TIMESTAMPS[2]="ends_0m08s"
TIMESTAMPS[3]="ends_0m12s"
TIMESTAMPS[4]="ends_0m16s"
TIMESTAMPS[5]="ends_0m20s"
TIMESTAMPS[6]="ends_0m24s"
TIMESTAMPS[7]="ends_0m28s"
TIMESTAMPS[8]="ends_0m32s"
TIMESTAMPS[9]="ends_0m36s"
TIMESTAMPS[10]="ends_0m40s"
TIMESTAMPS[11]="ends_0m44s"
TIMESTAMPS[12]="ends_0m48s"
TIMESTAMPS[13]="ends_0m52s"
TIMESTAMPS[14]="ends_0m56s"
TIMESTAMPS[15]="ends_1m00s"
TIMESTAMPS[16]="ends_1m04s"
TIMESTAMPS[17]="ends_1m08s"
TIMESTAMPS[18]="ends_1m12s"
TIMESTAMPS[19]="ends_1m16s"
TIMESTAMPS[20]="ends_1m20s"
TIMESTAMPS[21]="ends_1m24s"
TIMESTAMPS[22]="ends_1m28s"
TIMESTAMPS[23]="ends_1m32s"
TIMESTAMPS[24]="ends_1m36s"
TIMESTAMPS[25]="ends_1m40s"
TIMESTAMPS[26]="ends_1m44s"
TIMESTAMPS[27]="ends_1m48s"
TIMESTAMPS[28]="ends_1m52s"
TIMESTAMPS[29]="ends_1m56s"
TIMESTAMPS[30]="ends_2m00s"
TIMESTAMPS[31]="ends_2m04s"
TIMESTAMPS[32]="ends_2m08s"
TIMESTAMPS[33]="ends_2m12s"
TIMESTAMPS[34]="ends_2m16s"
TIMESTAMPS[35]="ends_2m20s"
TIMESTAMPS[36]="ends_2m24s"
TIMESTAMPS[37]="ends_2m28s"
TIMESTAMPS[38]="ends_2m32s"
TIMESTAMPS[39]="ends_2m36s"
TIMESTAMPS[40]="ends_2m40s"
TIMESTAMPS[41]="ends_2m44s"
TIMESTAMPS[42]="ends_2m48s"
TIMESTAMPS[43]="ends_2m52s"
TIMESTAMPS[44]="ends_2m56s"
TIMESTAMPS[45]="ends_3m00s"
TIMESTAMPS[46]="ends_3m04s"
TIMESTAMPS[47]="ends_3m08s"
TIMESTAMPS[48]="ends_3m12s"
TIMESTAMPS[49]="ends_3m16s"
TIMESTAMPS[50]="ends_3m20s"
TIMESTAMPS[51]="ends_3m24s"
TIMESTAMPS[52]="ends_3m28s"
TIMESTAMPS[53]="ends_3m32s"
TIMESTAMPS[54]="ends_3m36s"
TIMESTAMPS[55]="ends_3m40s"
TIMESTAMPS[56]="ends_3m44s"
TIMESTAMPS[57]="ends_3m48s"
TIMESTAMPS[58]="ends_3m52s"
TIMESTAMPS[59]="ends_3m56s"
TIMESTAMPS[60]="ends_4m00s"
TIMESTAMPS[61]="ends_4m04s"
TIMESTAMPS[62]="ends_4m08s"
TIMESTAMPS[63]="ends_4m12s"
TIMESTAMPS[64]="ends_4m16s"
TIMESTAMPS[65]="ends_4m20s"
TIMESTAMPS[66]="ends_4m24s"
TIMESTAMPS[67]="ends_4m28s"
TIMESTAMPS[68]="ends_4m32s"
TIMESTAMPS[69]="ends_4m36s"
TIMESTAMPS[70]="ends_4m40s"
TIMESTAMPS[71]="ends_4m44s"
TIMESTAMPS[72]="ends_4m48s"
TIMESTAMPS[73]="ends_4m52s"
TIMESTAMPS[74]="ends_4m56s"
TIMESTAMPS[75]="ends_5m00s"
TIMESTAMPS[76]="ends_5m04s"
TIMESTAMPS[77]="ends_5m08s"
TIMESTAMPS[78]="ends_5m12s"
TIMESTAMPS[79]="ends_5m16s"
TIMESTAMPS[80]="ends_5m20s"
TIMESTAMPS[81]="ends_5m24s"
TIMESTAMPS[82]="ends_5m28s"
TIMESTAMPS[83]="ends_5m32s"
TIMESTAMPS[84]="ends_5m36s"
TIMESTAMPS[85]="ends_5m40s"
TIMESTAMPS[86]="ends_5m44s"
TIMESTAMPS[87]="ends_5m48s"
TIMESTAMPS[88]="ends_5m52s"
TIMESTAMPS[89]="ends_5m56s"
TIMESTAMPS[90]="ends_6m00s"
TIMESTAMPS[91]="ends_6m04s"
TIMESTAMPS[92]="ends_6m08s"
TIMESTAMPS[93]="ends_6m12s"
TIMESTAMPS[94]="ends_6m16s"
TIMESTAMPS[95]="ends_6m20s"
TIMESTAMPS[96]="ends_6m24s"
TIMESTAMPS[97]="ends_6m28s"
TIMESTAMPS[98]="ends_6m32s"
TIMESTAMPS[99]="ends_6m36s"
TIMESTAMPS[100]="ends_6m40s"
TIMESTAMPS[101]="ends_6m44s"
TIMESTAMPS[102]="ends_6m48s"
TIMESTAMPS[103]="ends_6m52s"
TIMESTAMPS[104]="ends_6m56s"
TIMESTAMPS[105]="ends_7m00s"
TIMESTAMPS[106]="ends_7m04s"
TIMESTAMPS[107]="ends_7m08s"
TIMESTAMPS[108]="ends_7m12s"
TIMESTAMPS[109]="ends_7m16s"
TIMESTAMPS[110]="ends_7m20s"
TIMESTAMPS[111]="ends_7m24s"
TIMESTAMPS[112]="ends_7m28s"
TIMESTAMPS[113]="ends_7m32s"
TIMESTAMPS[114]="ends_7m36s"
TIMESTAMPS[115]="ends_7m40s"
TIMESTAMPS[116]="ends_7m44s"
TIMESTAMPS[117]="ends_7m48s"
TIMESTAMPS[118]="ends_7m52s"
TIMESTAMPS[119]="ends_7m56s"
TIMESTAMPS[120]="ends_8m00s"

TOTAL=120

count=0
for i in $(seq 1 $TOTAL); do
  gen "$i" "${PROMPTS[$i]}" &
  pids+=($!)
  count=$((count + 1))
  if [ $count -eq $BATCH_SIZE ]; then
    run_batch
    count=0
  fi
done
run_batch

echo ""
echo "All $TOTAL images generated! Check the output_mars/ folder."
