#!/bin/bash

HF=/opt/homebrew/lib/node_modules/@higgsfield/cli/vendor/hf
STYLE="Stick figure illustration rich vibrant colours. Thick uneven black outlines. Wobbly hand drawn lines. Stick figure humans with round heads dot eyes simple line bodies. Rich vibrant colourful backgrounds. Space scenes deep dark blue and purple backgrounds packed with bright white stars glowing suns blue and green Earth orange planets silver rockets. Handwritten labels and red arrows for emphasis. Objects simple but clearly recognisable. Lots of colour bright yellows electric blues vivid purples warm oranges glowing greens. Every scene feels alive with colour and energy. No realistic shading no 3D no white backgrounds. 16:9 aspect ratio."

mkdir -p output_hestia

gen() {
  local num=$1
  local prompt=$2
  local attempts=0
  echo "Generating image $num..."
  local job_id=""
  until [[ -n "$job_id" ]]; do
    job_id=$($HF generate create nano_banana_2 --prompt "${STYLE} ${prompt}" --json 2>/dev/null | tr -d '[]" \n')
    if [[ -z "$job_id" ]]; then
      attempts=$((attempts + 1))
      if [ $attempts -ge 3 ]; then
        echo "FAILED image $num after 3 attempts"
        return
      fi
      echo "Retrying image $num (attempt $attempts)..."
      sleep 5
    fi
  done
  echo "Waiting for image $num..."
  $HF generate wait "$job_id" > "output_hestia/image_${num}.txt" 2>&1
  echo "Done $num"
}

BATCH_SIZE=10
pids=()

run_batch() {
  for pid in "${pids[@]}"; do
    wait "$pid"
  done
  pids=()
}

declare -A PROMPTS

PROMPTS[1]="Three stick figure scientists at a table covered in planet blueprints and diagrams. DESIGNED FROM SCRATCH label bold. Deep purple space background with stars. Red arrows everywhere."
PROMPTS[2]="NOT DISCOVERED in bold handwritten text with big red X through a telescope. DESIGNED label enormous bold letters filling frame. Dark purple background. Dramatic composition."
PROMPTS[3]="Four stick figure scientists sitting with giant books labelled BIOLOGY EVOLUTION PLANETARY SCIENCE. Huge glowing question mark floating above. ONE QUESTION label. Deep dark blue space."
PROMPTS[4]="Glowing idealised planet floating in space radiating golden light. PERFECT PLANET FOR LIFE label large handwritten. Stick figure with wide eyes and open arms looking up in awe. Deep purple star filled background."
PROMPTS[5]="Small dull Earth on left. Enormous glowing magnificent planet on right labelled THE ANSWER. Stick figure between them with dropped jaw shocked face. BEYOND EARTH label. NEVER LOOK THE SAME label."
PROMPTS[6]="Giant glowing planet centre frame with HESTIA written boldly across it in handwritten letters. Dramatic golden orange glow. Deep purple star-filled space. Red arrows pointing at planet. THEY CALLED IT HESTIA label."
PROMPTS[7]="Large glowing SUBSCRIBE button centre frame. Stick figure eagerly pressing it. UNKNOWN ORIGINS label bold. Stars and planets background. SUBSCRIBE RIGHT NOW label. Bright yellows and electric blues."
PROMPTS[8]="Screen split showing deep space on top and deep ocean on bottom. SPACE MYSTERIES and DEEP OCEAN MYSTERIES labels. STRANGEST MOST MIND BENDING MYSTERIES label. Stick figure host presenting vivid colours."
PROMPTS[9]="Stick figure squirming and sweating with uncomfortable expression. SOMETHING UNCOMFORTABLE label bold. EARTH IS NOT THE BEST PLANET FOR LIFE label bold red. Anxious red zigzag lines. Dark blue purple background stars."
PROMPTS[10]="Earth centre frame with big red X over it. NOT THE BEST PLANET FOR LIFE label bold. IT'S JUST THE ONLY ONE WE'VE FOUND label. Earth looks sad droopy face. Other planets in background looking superior."
PROMPTS[11]="Two signs side by side. ONLY ONE WE FOUND and BEST PLANET FOR LIFE. Stick figure between them arms wide apart. VERY DIFFERENT THINGS label. MOST OF OUR PLANET IS ACTUALLY HOSTILE label. Dark space."
PROMPTS[12]="Earth split into hostile zones. Ice zone desert zone toxic zone labelled. HOSTILE label bold red. FREEZING POLAR REGIONS label. THOUSANDS OF KM label with long red arrow. Shivering stick figure in snow."
PROMPTS[13]="Enormous scorching desert stretching to horizon. Giant burning yellow sun blazing down. SCORCHING DESERTS label. ALMOST NOTHING LIVING label. Stick figure melting with sweat drops. One tiny dead cactus."
PROMPTS[14]="Cross section of ocean. Bright sunlight zone at top with fish. SUNLIGHT label. Below halfway line pitch black. OCEANS SO DEEP SUNLIGHT NEVER REACHES BOTTOM label. Deep blues. HUGE AMOUNTS OF WASTED SPACE label."
PROMPTS[15]="Enormous blazing yellow Sun filling most of frame. AND OUR SUN label dramatic. Chain attached to Earth pulling it back. HOLDING US BACK label. MIGHT ACTUALLY BE HOLDING US BACK label. Dark purple space stars."
PROMPTS[16]="Our Sun centre frame with YELLOW DWARF label bold. IT BURNS BRIGHT AND HOT label. BUT BURNS THROUGH ITS FUEL FAST label. Fuel gauge attached showing nearly empty. Warning light flashing. Scientist worried."
PROMPTS[17]="Enormous swollen red Sun expanding to swallow tiny Earth. Earth disappearing into Sun. IN ABOUT 5 BILLION YEARS label. EXPAND AND SWALLOW THE EARTH WHOLE label. Stick figure running screaming. Dramatic reds."
PROMPTS[18]="Enormous long timeline stretching across frame. 4 BILLION YEARS label. Tiny dot near very end labelled US — WE ARE HERE. LIFE TOOK 4 BILLION YEARS JUST TO GET HERE label. THE UNIVERSE USED EVERY SECOND label."
PROMPTS[19]="Warm glowing orange star on right labelled A BETTER STAR. Yellow Sun on left looking inferior. A BETTER STAR WOULD BE AN ORANGE DWARF label. COOLER MORE STABLE label. Deep dark space background stars."
PROMPTS[20]="ORANGE DWARFS LIVE FOR UP TO 70 BILLION YEARS label filling frame dramatically. Warm glowing orange dwarf star. Giant bold handwritten 70 BILLION YEARS. Stick figure with jaw dropped. SEVENTY BILLION label."
PROMPTS[21]="Bar chart. Sun lifespan as short bar. Orange dwarf as enormous bar 7 times taller off the chart. SEVEN TIMES LONGER THAN OUR SUN label bold. x7 label circled. Stick figure scientist with pointer."
PROMPTS[22]="Two planets on parallel timelines. Earth timeline ends with X. Orange dwarf planet timeline continues with 66 BILLION YEARS REMAINING label. STILL EVOLVING label on orange planet. Earth done."
PROMPTS[23]="Enormous glowing question mark filling frame. THINK ABOUT WHAT 66 BILLION MORE YEARS OF EVOLUTION PRODUCES label. Tiny stick figure below arms spread wide in total awe. WE HAVE NO IDEA label. WE DON'T HAVE THE WORDS YET."
PROMPTS[24]="Beautiful Hestia planet in foreground with warm glowing orange dwarf star behind it. HESTIA ORBITS AN ORANGE DWARF label with red arrow. NOW LET'S TALK ABOUT THE PLANET ITSELF label. Deep purple star-filled space."
PROMPTS[25]="Stick figure leaning in with wide eyes and nervous grin. THIS IS WHERE IT GETS UNSETTLING label wobbly text. Hestia planet glowing. HESTIA IS 1.3 TIMES THE SIZE OF EARTH label bold. Eerie purple glow."
PROMPTS[26]="Earth and Hestia side by side. Hestia noticeably larger. 1.3 TIMES THE SIZE label with red arrow. 70 PERCENT MORE SURFACE AREA label. MORE ROOM FOR ECOSYSTEMS label. Stick figure with ruler measuring."
PROMPTS[27]="Hestia cross section showing every niche packed with life. MORE ROOM FOR EVOLUTION TO EXPERIMENT label. MORE ROOM FOR LIFE TO FILL EVERY POSSIBLE NICHE label. Ocean mountains jungles all crammed with creatures. Vivid."
PROMPTS[28]="Earth scoreboard showing 9 MILLION SPECIES over 4 BILLION YEARS. Hestia scoreboard exploding with HUNDREDS OF MILLIONS label. ON EARTH label vs ON HESTIA label. SCIENTISTS ESTIMATE label. Jaw dropped stick figure."
PROMPTS[29]="NOT 9 MILLION in huge text with red X. HUNDREDS OF MILLIONS OF COMPLEX SPECIES label exploding with creatures. THAT IS NOT A BETTER VERSION OF EARTH label. COMPLETELY DIFFERENT CATEGORY label bold."
PROMPTS[30]="Hestia planet with architect blueprint overlay showing every feature with design tick marks. EVERY SINGLE FEATURE DESIGNED TO MAXIMISE LIFE label. DESIGNED label. AND WHEN YOU HEAR EACH ONE label. Stick figure engineer."
PROMPTS[31]="Earth covered in red mistake labels and X marks. HOW MANY MISTAKES EARTH IS MAKING label. LET'S START WITH THE CONTINENTS label bold. Simple map of Earth with vast interiors highlighted. Too big label."
PROMPTS[32]="Map cross section. Near ocean green and wet with plants. Far inland increasingly dry. THE FURTHER FROM OCEAN THE LESS RAINFALL label. LESS RAINFALL THE MORE DESERT label. Gradient green to brown to dead."
PROMPTS[33]="Three panels. SAHARA in bold letters burning yellow sand. GOBI grey empty barren desert. AUSTRALIAN OUTBACK red earth. All three labelled. THOUSANDS OF KM OF LAND THAT SUPPORTS ALMOST NOTHING label across all."
PROMPTS[34]="Earth map with large grey dead zones. ON EARTH VAST STRETCHES OF SURFACE ESSENTIALLY DEAD label. HESTIA HAS NO MASSIVE CONTINENTS label bold with green tick. Small landmasses dotted across ocean instead."
PROMPTS[35]="Beautiful chain of islands and archipelagos across Hestia. INSTEAD DOZENS OF SMALLER LANDMASSES label. ISLANDS AND ARCHIPELAGOS SPREAD ACROSS ENTIRE PLANET label. Each island lush green. Deep vivid blue ocean."
PROMPTS[36]="Hestia island map with distance arrows from every point to nearest ocean all short. EVERY SINGLE PIECE OF LAND SURROUNDED BY WATER label. NO POINT ON HESTIA EVER FAR FROM THE OCEAN label. Blue everywhere."
PROMPTS[37]="Desert symbol with huge red X. NO DESERTS label bold with green tick. NO BARREN INTERIORS label. EVERY PIECE OF LAND WARM WET AND ALIVE label. Lush green tropical replacing desert. Stick figure dancing happily."
PROMPTS[38]="Hestia coastline glowing golden. AND THE COASTLINE OF HESTIA label. 45 TIMES LONGER THAN EARTH'S label bold. Bar comparison showing 45x bar going off chart. 45 TIMES label enormous text. Coastlines where life explodes."
PROMPTS[39]="Coastal zone showing coral reef estuaries and mangroves all crammed together at coast. RICHEST ECOSYSTEMS ON EARTH ALL SIT WHERE LAND MEETS OCEAN label. Fish birds plants sea creatures all gathered. Vivid blues greens."
PROMPTS[40]="Hestia planet with glowing golden coastline border stretching millions of km in every direction. ON HESTIA THAT BORDER STRETCHES FOR MILLIONS OF KILOMETRES label. Tiny stick figure against massive scale. Awe inspiring."
PROMPTS[41]="Hestia ocean surface with mysterious strange glow beneath. THE OCEANS OF HESTIA ARE WHERE THINGS GET REALLY STRANGE label. EARTH'S OCEANS HAVE A PROBLEM ALMOST NOBODY TALKS ABOUT label. Stick figure peering nervously."
PROMPTS[42]="Ocean cross section. THEY'RE TOO DEEP label dramatic bold. THE AVERAGE DEPTH IS 3700 METRES label with measurement arrow. Tiny stick figure at surface for scale. Deep dark blue below. AVERAGE DEPTH label numbers bold."
PROMPTS[43]="Ocean cross section. Bright sunlight rays penetrating down to 200 METRES line. SUNLIGHT ONLY PENETRATES 200 METRES label. Clear cutoff line. Above line bright fish. BELOW THAT TOTAL DARKNESS label. Pitch black below."
PROMPTS[44]="Dark ocean floor with gravestones in seabed. A GRAVEYARD label dramatic. AND IN THAT DARKNESS ALMOST NOTHING CAN PHOTOSYNTHESISE label. ALMOST NOTHING CAN GROW label. COLD DARK SILENT VOID label. Darkest blues blacks."
PROMPTS[45]="Hestia ocean cross section glowing bright with warmth and life. HESTIA'S OCEANS ARE COMPLETELY DIFFERENT label bold. THEY'RE SHALLOW label dramatic. AVERAGING JUST 100 TO 200 METRES DEEP label. Vivid blues greens."
PROMPTS[46]="Bright golden sunlight rays penetrating all the way to Hestia ocean floor. SUNLIGHT REACHES THE BOTTOM label bold. THE WHOLE SEAFLOOR IS A SUNLIT REEF label. Coral everywhere glowing. Every inch alive and vivid."
PROMPTS[47]="Coral reef stretching to horizon in every direction. IMAGINE CORAL STRETCHING FOR THOUSANDS OF KILOMETRES label. THE ENTIRE OCEAN ALIVE label bold. EVERY PART OF IT COMPETING EVOLVING GROWING label. Overwhelming abundance."
PROMPTS[48]="Two ocean cross sections. Earth thin bright sliver at top with enormous dark dead mass below. Hestia entirely bright floor to ceiling. ON EARTH A THIN SLIVER label vs ON HESTIA IT IS THE ENTIRE OCEAN label bold."
PROMPTS[49]="Side by side thermometers. Earth lower. Hestia 5 degrees higher circled red. HESTIA RUNS 5 DEGREES WARMER label. DOESN'T SOUND LIKE MUCH label casual shrug. BUT IT PUSHES MOST OF PLANET INTO TROPICAL RAINFOREST label."
PROMPTS[50]="Earth globe with tiny 10% highlighted green as rainforest. TROPICAL RAINFORESTS COVER JUST 10 PERCENT label red arrow. BUT CONTAIN 50 PERCENT OF ALL SPECIES label bold. Creatures packed into small zone overflowing."
PROMPTS[51]="Hestia planet entirely covered in lush dense tropical rainforest. ON HESTIA THAT DENSITY OF LIFE COVERS EVERYTHING label. EVERY ISLAND EVERY COAST EVERY SHALLOW SEA label bold. Green overflowing the entire planet."
PROMPTS[52]="Hestia planet with glowing thick atmosphere layer. AND THEN THERE'S THE ATMOSPHERE label dramatic. HESTIA'S GRAVITY IS 20 PERCENT STRONGER label. HOLDS A MUCH THICKER ATMOSPHERE label. Electric blue atmosphere glow."
PROMPTS[53]="Atmosphere pressure gauge at 1.5 times Earth level. ONE AND A HALF TIMES THE ATMOSPHERIC PRESSURE label. RICHER IN OXYGEN label. RICHER IN CARBON DIOXIDE label. Plants growing faster below. CO2 molecules floating. Vivid."
PROMPTS[54]="Plants growing at super speed with motion lines. PLANTS GROW FASTER label. Trees impossibly tall going off top of frame. TREES GROW TALLER label upward arrow. Lush greens everywhere. AND INSECTS label dramatic appearing."
PROMPTS[55]="Earth insect with breathing tube diagram showing size limit cap. ON EARTH INSECTS LIMITED IN SIZE label. SIZE LIMIT label with cap. ON HESTIA WITH THICKER ATMOSPHERE INSECTS COULD GROW TO SIZES WE HAVE NEVER SEEN label."
PROMPTS[56]="Enormous insects towering over tiny stick figures on Hestia. Giant beetle and dragonfly filling frame. Stick figures looking up in shock. SIZES WE HAVE NEVER SEEN label. Thick glowing atmosphere above. Vivid dramatic."
PROMPTS[57]="Six-legged creature size of horse striding through dense Hestia forest. SIX LEGGED QUADRUPEDS THE SIZE OF HORSES label. Stick figure tiny beside it for scale. THE LARGEST LAND CREATURES ON HESTIA label bold."
PROMPTS[58]="Forest of impossibly tall dense trees towering far above frame. MOVING THROUGH FORESTS DENSER AND TALLER THAN ANYTHING THAT HAS EVER EXISTED ON EARTH label. Giant creatures moving through trunks. Tiny stick figure. Vivid greens."
PROMPTS[59]="Hestia planet with giant clock showing 36 HOURS. AND HESTIA'S DAY IS 36 HOURS LONG label. MORE SUNLIGHT EVERY SINGLE DAY label. Sun arc across sky much longer than Earth 24 hour arc. MORE PHOTOSYNTHESIS label."
PROMPTS[60]="MORE ENERGY PUMPING THROUGH EVERY ECOSYSTEM label. Energy flow lines glowing through entire Hestia ecosystem. Every system connected. MORE ENERGY label bold. Electric yellows and oranges. Arrows showing energy flow everywhere."
PROMPTS[61]="Hestia with all systems shown as connected gears. Star oceans continents atmosphere all linked. EVERY SINGLE SYSTEM WORKING TOGETHER label. THE STAR label. THE SIZE label. THE CONTINENTS label. THE OCEANS label. All ticked."
PROMPTS[62]="THE TEMPERATURE label. THE ATMOSPHERE label. ALL OF IT OPTIMISED label bold. ALL OF IT POINTING IN ONE DIRECTION label. MORE LIFE label. MORE COMPLEXITY label. MORE EVOLUTION label. FOR LONGER THAN WE CAN IMAGINE label."
PROMPTS[63]="Stick figure lying in bed eyes wide open cannot sleep. AND HERE IS THE THOUGHT THAT SHOULD KEEP YOU UP TONIGHT label. Night sky stars through window. Glowing thought bubble. Anxious expression. Blue night scene."
PROMPTS[64]="Hestia planet going transparent and ghostly. HESTIA ISN'T REAL label shocking bold. Planet fading to outline. SCIENTISTS DESIGNED IT label. Stick figure reaching out as it fades. Dramatic empty space where Hestia was."
PROMPTS[65]="Universe map showing each Hestia feature as real things confirmed. Orange dwarf stars circled green. Shallow ocean planets labelled. Thick atmosphere planets shown. BUT THE CONDITIONS THAT MAKE HESTIA POSSIBLE label. ALL EXIST label bold."
PROMPTS[66]="Multiple exoplanets orbiting warm orange dwarf stars. WE HAVE FOUND EXOPLANETS ORBITING ORANGE DWARFS label. Telescope beam highlighting them. Green tick marks. WE HAVE FOUND PLANETS WITH THICK ATMOSPHERES label. Discovery."
PROMPTS[67]="Giant scoreboard counter showing 6000 PLUS EXOPLANETS CONFIRMED. WE HAVE CONFIRMED OVER 6000 EXOPLANETS label. WE HAVE ONLY LOOKED AT A TINY FRACTION OF THE SKY label. Enormous sky map with tiny fraction highlighted."
PROMPTS[68]="Hundreds of billions of galaxies filling entire frame. THE UNIVERSE HAS HUNDREDS OF BILLIONS OF GALAXIES label. EACH ONE CONTAINING HUNDREDS OF BILLIONS OF STARS label. MOST OF THOSE STARS HAVE PLANETS label. Overwhelming scale."
PROMPTS[69]="Odds meter showing near zero probability. THE ODDS THAT SOMETHING LIKE HESTIA DOESN'T EXIST label. ESSENTIALLY ZERO label dramatic. IT ALMOST CERTAINLY EXISTS label bold green. PROBABLY MANY TIMES OVER label. Multiple Hestia planets."
PROMPTS[70]="Telescope scanning dark space. WE JUST HAVEN'T FOUND IT YET label. YET label bold underlined. AND WHEN WE DO label. THE QUESTION WON'T JUST BE WHETHER LIFE IS THERE label. New enormous question mark appearing."
PROMPTS[71]="Giant mysterious silhouette of unknown evolved creature on Hestia. THE QUESTION WILL BE WHAT 70 BILLION YEARS OF EVOLUTION ON A PLANET PERFECTLY BUILT FOR LIFE ACTUALLY PRODUCES label. Stick figure tiny looking up in awe and dread."
PROMPTS[72]="Earth with PRETTY AVERAGE PLANET label. WE HAD 4 BILLION YEARS ON A PRETTY AVERAGE PLANET label. AND WE BUILT CITIES label with stick figure city skyline. AND MUSIC label with colourful musical notes dancing. Achievement visual."
PROMPTS[73]="Giant telescope with beam reaching across space to illuminate distant exoplanet. AND TELESCOPES POWERFUL ENOUGH TO FIND OTHER WORLDS label. Stick figure at telescope excited. IMAGINE WHAT 70 BILLION YEARS ON HESTIA LOOKS LIKE label."
PROMPTS[74]="Stick figure with top of head open infinite possibilities exploding outward. WE DON'T HAVE THE WORDS FOR IT label. NOT YET label hopeful. Pencil hovering over blank page. Telescope pointing toward future. Stars and Hestia glowing."
PROMPTS[75]="Like button and Subscribe button glowing. UNKNOWN ORIGINS label bold. IF THIS VIDEO MADE YOU FEEL SOMETHING LIKE IT label. DROP A COMMENT label. DO YOU THINK A PLANET LIKE HESTIA ALREADY EXISTS label. WHAT DO YOU THINK IT PRODUCED label."
PROMPTS[76]="Stick figure waving goodbye big happy expression. WELL SEE YOU IN THE NEXT ONE label. Stars and Hestia-like planet glowing in background. Warm inviting vivid colours. Unknown Origins feel. WE DON'T HAVE THE WORDS YET label."

# Extra scenes to reach 120 spread evenly through the story
PROMPTS[77]="Stick figure pointing urgently at glowing Hestia planet. AND WE NEED TO TALK ABOUT IT label. WE ARE ONLY JUST GETTING STARTED label. Exclamation marks everywhere. Electric blue and purple space. Red arrows. Vivid."
PROMPTS[78]="Stick figure with hands on hips grinning confidently. BECAUSE WHAT YOU'RE ABOUT TO HEAR IS JUST THE BEGINNING label. YOU DO NOT WANT TO MISS WHAT'S COMING label. Exciting energetic. Stars and planets background."
PROMPTS[79]="Two signs. ONLY PLANET WE FOUND and BEST PLANET FOR LIFE. Big gap between them. AND THOSE ARE VERY DIFFERENT THINGS label bold. Stick figure showing the gap. Space background. VERY DIFFERENT label circled red."
PROMPTS[80]="Sun with halo. THE THING WE'VE BEEN TOLD IS THE SOURCE OF ALL LIFE label. Plants flowers creatures around Sun worshipping it. HERE'S WHY IT MIGHT BE HOLDING US BACK label appearing. Dark space."
PROMPTS[81]="Our Sun is a yellow dwarf star. IT BURNS BRIGHT AND HOT label. IN ABOUT 5 BILLION YEARS IT WILL EXPAND label. THAT SOUNDS LIKE A LONG TIME label. Stick figure nodding casually. But warning symbols in corners."
PROMPTS[82]="THE UNIVERSE USED ALMOST EVERY SECOND OF THAT WINDOW TO PRODUCE US label. Timeline with tiny dot at end labelled US. Giant Universe figure with clock. A BETTER STAR WOULD BE AN ORANGE DWARF label appearing."
PROMPTS[83]="Orange dwarf star cooling slowly and stably. COOLER MORE STABLE label. HERE'S THE PART THAT SHOULD STOP YOU IN YOUR TRACKS label. Stick figure frozen mid stride. STOP label. Dramatic freeze frame. Vivid electric blue."
PROMPTS[84]="SO IF LIFE STARTED ON A PLANET ORBITING AN ORANGE DWARF AT THE SAME TIME AS EARTH label. Two planet comparison. THAT PLANET WOULD STILL HAVE 66 BILLION YEARS LEFT label. KEEP EVOLVING label. Jaw dropped stick figure."
PROMPTS[85]="WE DON'T HAVE THE WORDS FOR IT YET label on blank dictionary page. HESTIA ORBITS AN ORANGE DWARF label. NOW LET'S TALK ABOUT THE PLANET ITSELF label. Hestia revealed glowing. AND THIS IS WHERE IT GETS UNSETTLING label."
PROMPTS[86]="Hestia surface showing 70 PERCENT MORE SURFACE AREA. MORE ROOM FOR ECOSYSTEMS TO DEVELOP label. MORE ROOM FOR EVOLUTION TO EXPERIMENT label. Multiple diverse habitats growing on extra land. Vivid greens and blues."
PROMPTS[87]="THAT IS NOT A BETTER VERSION OF EARTH label bold. THAT IS A COMPLETELY DIFFERENT CATEGORY OF PLANET label. Earth on lower podium. Hestia on separate elevated tier. DIFFERENT LEAGUE label. COMPLETELY DIFFERENT label."
PROMPTS[88]="BUT HERE'S WHAT'S REALLY STRANGE ABOUT HESTIA label. IT DOESN'T JUST HAVE MORE LIFE BECAUSE IT'S BIGGER label. Stick figure with raised eyebrow. Every feature with design tick marks. EVERY FEATURE DESIGNED label."
PROMPTS[89]="HERE'S A FLAW IN EARTH THAT MOST PEOPLE NEVER THINK ABOUT label. OUR CONTINENTS ARE TOO BIG label bold. Map showing continents. THE FURTHER YOU GET FROM THE OCEAN label. Less rainfall gradient shown. LESS RAINFALL MORE DESERT."
PROMPTS[90]="ON EARTH VAST STRETCHES OF SURFACE ESSENTIALLY DEAD label. HESTIA HAS NO MASSIVE CONTINENTS label bold green tick. INSTEAD IT HAS DOZENS OF SMALLER LANDMASSES label. Islands and archipelagos beautiful pattern. Vivid blues."
PROMPTS[91]="EVERY SINGLE PIECE OF LAND SURROUNDED BY WATER label. NO POINT ON HESTIA EVER FAR FROM THE OCEAN label. WHICH MEANS NO DESERTS label bold green tick. NO BARREN INTERIORS label. EVERY PIECE OF LAND WARM WET ALIVE label."
PROMPTS[92]="AND THE COASTLINE OF HESTIA label. 45 TIMES LONGER THAN EARTH'S label enormous. 45 TIMES label filling frame explosion of colour. AND COASTLINES ARE WHERE LIFE EXPLODES label. CORAL REEFS ESTUARIES MANGROVES label. Vivid."
PROMPTS[93]="ON HESTIA THAT BORDER STRETCHES FOR MILLIONS OF KILOMETRES IN EVERY DIRECTION label. BUT WE'RE ONLY JUST GETTING STARTED label. BECAUSE THE OCEANS OF HESTIA ARE WHERE THINGS GET REALLY STRANGE label. Mystery glow."
PROMPTS[94]="EARTH'S OCEANS HAVE A PROBLEM ALMOST NOBODY TALKS ABOUT label. THEY'RE TOO DEEP label dramatic. THE AVERAGE DEPTH OF OUR OCEANS IS 3700 METRES label. BUT SUNLIGHT ONLY PENETRATES ABOUT 200 METRES DOWN label. Cutoff line."
PROMPTS[95]="BELOW THAT TOTAL DARKNESS label dramatic. AND IN THAT DARKNESS ALMOST NOTHING CAN PHOTOSYNTHESISE label. THE VAST MAJORITY OF EARTH'S OCEAN FLOOR IS A COLD DARK SILENT VOID label. A GRAVEYARD label. Dark blacks blues."
PROMPTS[96]="HESTIA'S OCEANS ARE COMPLETELY DIFFERENT label. THEY'RE SHALLOW label bold. AVERAGING JUST 100 TO 200 METRES DEEP label. SUNLIGHT REACHES THE BOTTOM label. THE WHOLE SEAFLOOR IS A SUNLIT REEF label. Bright vivid colours."
PROMPTS[97]="IMAGINE CORAL STRETCHING FOR THOUSANDS OF KILOMETRES IN EVERY DIRECTION label. THE ENTIRE OCEAN ALIVE label. EVERY PART OF IT PRODUCTIVE label. EVERY PART COMPETING EVOLVING GROWING label. Overwhelming abundance vivid reef."
PROMPTS[98]="ON EARTH THE SHALLOW SUNLIT ZONE IS A THIN SLIVER label vs ON HESTIA IT IS THE ENTIRE OCEAN label. NOW THE TEMPERATURE label. HESTIA RUNS 5 DEGREES WARMER THAN EARTH ON AVERAGE label. Two planet comparison warm cool."
PROMPTS[99]="5 DEGREES DOESN'T SOUND LIKE MUCH label shrug. BUT IT PUSHES MOST OF THE PLANET INTO TROPICAL RAINFOREST CONDITIONS label bold. TROPICAL RAINFORESTS COVER JUST 10 PERCENT OF EARTH'S SURFACE label with tiny highlighted zone."
PROMPTS[100]="BUT THEY CONTAIN 50 PERCENT OF ALL SPECIES ON THE PLANET label. ON HESTIA THAT DENSITY OF LIFE COVERS EVERYTHING label bold. EVERY ISLAND EVERY COAST EVERY SHALLOW SEA label. And then there's the atmosphere label dramatic."
PROMPTS[101]="HESTIA'S GRAVITY IS 20 PERCENT STRONGER label. MEANS IT CAN HOLD A MUCH THICKER ATMOSPHERE label. ONE AND A HALF TIMES THE ATMOSPHERIC PRESSURE OF EARTH label. RICHER IN OXYGEN label. RICHER IN CO2 label. Plants thriving."
PROMPTS[102]="PLANTS GROW FASTER label. TREES GROW TALLER label upward arrow off frame. AND INSECTS label dramatic. ON EARTH INSECTS LIMITED IN SIZE BECAUSE OF WAY THEY BREATHE label diagram. ON HESTIA INSECTS COULD GROW TO SIZES NEVER SEEN label."
PROMPTS[103]="THE LARGEST LAND CREATURES ON HESTIA COULD POTENTIALLY BE SIX LEGGED QUADRUPEDS THE SIZE OF HORSES label. Moving through forests denser and taller than anything that has ever existed on Earth. Enormous six-legged creature shown."
PROMPTS[104]="AND HESTIA'S DAY IS 36 HOURS LONG label. MORE SUNLIGHT EVERY SINGLE DAY label. MORE PHOTOSYNTHESIS label. MORE ENERGY PUMPING THROUGH EVERY ECOSYSTEM ON THE PLANET label. Energy flow lines glowing. Electric yellows."
PROMPTS[105]="EVERY SINGLE SYSTEM WORKING TOGETHER label. THE STAR label orange dwarf glowing. THE SIZE label Hestia larger. THE CONTINENTS label island chain. THE OCEANS label shallow sunlit reef. All connected gears ticking perfectly."
PROMPTS[106]="THE TEMPERATURE label warm tropical. THE ATMOSPHERE label thick glowing blue. ALL OF IT OPTIMISED label bold all ticks. ALL OF IT POINTING IN ONE DIRECTION label arrow. MORE LIFE MORE COMPLEXITY MORE EVOLUTION label bold."
PROMPTS[107]="FOR LONGER THAN WE CAN IMAGINE label infinite timeline off frame. AND HERE IS THE THOUGHT THAT SHOULD KEEP YOU UP TONIGHT label. Stick figure in bed eyes open. HESTIA ISN'T REAL label shocking. SCIENTISTS DESIGNED IT label."
PROMPTS[108]="BUT THE CONDITIONS THAT MAKE HESTIA POSSIBLE label. ORANGE DWARF STARS label circled. SHALLOW OCEANS label. ARCHIPELAGO WORLDS label. THICK ATMOSPHERES label. ALL OF THESE THINGS EXIST IN THE UNIVERSE label bold. Universe map."
PROMPTS[109]="WE HAVE FOUND EXOPLANETS ORBITING ORANGE DWARFS label. WE HAVE FOUND PLANETS WITH THICK ATMOSPHERES label. WE HAVE FOUND PLANETS IN THE HABITABLE ZONE label. WE HAVE CONFIRMED OVER 6000 EXOPLANETS label. Ticks on each."
PROMPTS[110]="AND WE HAVE ONLY LOOKED AT A TINY FRACTION OF THE SKY label. THE UNIVERSE HAS HUNDREDS OF BILLIONS OF GALAXIES label. EACH ONE CONTAINING HUNDREDS OF BILLIONS OF STARS label. MOST OF THOSE STARS HAVE PLANETS label. Overwhelming."
PROMPTS[111]="THE ODDS THAT SOMETHING LIKE HESTIA DOESN'T EXIST OUT THERE ARE ESSENTIALLY ZERO label. IT ALMOST CERTAINLY EXISTS label bold green. PROBABLY MANY TIMES OVER label. WE JUST HAVEN'T FOUND IT YET label. Telescope scanning space."
PROMPTS[112]="AND WHEN WE DO THE QUESTION WON'T JUST BE WHETHER LIFE IS THERE label. THE QUESTION WILL BE WHAT 70 BILLION YEARS OF EVOLUTION ON A PLANET PERFECTLY BUILT FOR LIFE ACTUALLY PRODUCES label. Giant mystery silhouette looming."
PROMPTS[113]="WE HAD 4 BILLION YEARS ON A PRETTY AVERAGE PLANET label. AND WE BUILT CITIES label with stick figure skyline. AND MUSIC label with dancing musical notes. AND TELESCOPES POWERFUL ENOUGH TO FIND OTHER WORLDS label. Stick figure proud."
PROMPTS[114]="IMAGINE WHAT 70 BILLION YEARS ON HESTIA LOOKS LIKE label. WE DON'T HAVE THE WORDS FOR IT label. NOT YET label hopeful bold. Stick figure looking through telescope toward stars. Future feeling. Electric blues warm yellows."
PROMPTS[115]="IF THIS VIDEO MADE YOU FEEL SOMETHING LIKE IT AND SUBSCRIBE TO UNKNOWN ORIGINS label. DROP A COMMENT label. DO YOU THINK A PLANET LIKE HESTIA ALREADY EXISTS OUT THERE label. WHAT DO YOU THINK IT PRODUCED label. Stars background."
PROMPTS[116]="Stick figure waving goodbye big happy expression. WE'LL SEE YOU IN THE NEXT ONE label. Stars and Hestia-like planet glowing in background. Warm invid vivid colours. Unknown Origins channel feel."

# Fill remaining to 120 with key visual moments
PROMPTS[117]="HESTIA in enormous glowing letters filling frame. The perfect planet for life. Deep purple space. Stars all around. Orange dwarf star behind it. Golden warm glow. Dramatic reveal. THIS IS HESTIA label bold."
PROMPTS[118]="Scientists designed a planet from scratch. Blueprint of Hestia showing every optimised feature. DESIGNED FOR LIFE label. All features labelled with green ticks. Star oceans continents atmosphere temperature. Complete blueprint."
PROMPTS[119]="Earth vs Hestia final comparison. Earth labelled PRETTY GOOD. Hestia labelled PERFECTLY DESIGNED FOR LIFE. Side by side dramatic comparison. All features compared with arrows. THAT'S THE DIFFERENCE label bold. Vivid dramatic."
PROMPTS[120]="Unknown Origins channel logo with stars and space background. SUBSCRIBE label. EVERY VIDEO IS ANOTHER WORLD label. ANOTHER MYSTERY label. ANOTHER PLACE THE UNIVERSE FORGOT TO MAKE SAFE label. See you next time. Vivid warm."

declare -A TIMESTAMPS
TIMESTAMPS[1]="ends_0m04s"
TIMESTAMPS[2]="ends_0m07s"
TIMESTAMPS[3]="ends_0m11s"
TIMESTAMPS[4]="ends_0m14s"
TIMESTAMPS[5]="ends_0m18s"
TIMESTAMPS[6]="ends_0m22s"
TIMESTAMPS[7]="ends_0m25s"
TIMESTAMPS[8]="ends_0m29s"
TIMESTAMPS[9]="ends_0m32s"
TIMESTAMPS[10]="ends_0m36s"
TIMESTAMPS[11]="ends_0m40s"
TIMESTAMPS[12]="ends_0m43s"
TIMESTAMPS[13]="ends_0m47s"
TIMESTAMPS[14]="ends_0m50s"
TIMESTAMPS[15]="ends_0m54s"
TIMESTAMPS[16]="ends_0m57s"
TIMESTAMPS[17]="ends_1m01s"
TIMESTAMPS[18]="ends_1m05s"
TIMESTAMPS[19]="ends_1m08s"
TIMESTAMPS[20]="ends_1m12s"
TIMESTAMPS[21]="ends_1m15s"
TIMESTAMPS[22]="ends_1m19s"
TIMESTAMPS[23]="ends_1m23s"
TIMESTAMPS[24]="ends_1m26s"
TIMESTAMPS[25]="ends_1m30s"
TIMESTAMPS[26]="ends_1m33s"
TIMESTAMPS[27]="ends_1m37s"
TIMESTAMPS[28]="ends_1m41s"
TIMESTAMPS[29]="ends_1m44s"
TIMESTAMPS[30]="ends_1m48s"
TIMESTAMPS[31]="ends_1m51s"
TIMESTAMPS[32]="ends_1m55s"
TIMESTAMPS[33]="ends_1m59s"
TIMESTAMPS[34]="ends_2m02s"
TIMESTAMPS[35]="ends_2m06s"
TIMESTAMPS[36]="ends_2m09s"
TIMESTAMPS[37]="ends_2m13s"
TIMESTAMPS[38]="ends_2m17s"
TIMESTAMPS[39]="ends_2m20s"
TIMESTAMPS[40]="ends_2m24s"
TIMESTAMPS[41]="ends_2m27s"
TIMESTAMPS[42]="ends_2m31s"
TIMESTAMPS[43]="ends_2m34s"
TIMESTAMPS[44]="ends_2m38s"
TIMESTAMPS[45]="ends_2m42s"
TIMESTAMPS[46]="ends_2m45s"
TIMESTAMPS[47]="ends_2m49s"
TIMESTAMPS[48]="ends_2m52s"
TIMESTAMPS[49]="ends_2m56s"
TIMESTAMPS[50]="ends_3m00s"
TIMESTAMPS[51]="ends_3m03s"
TIMESTAMPS[52]="ends_3m07s"
TIMESTAMPS[53]="ends_3m10s"
TIMESTAMPS[54]="ends_3m14s"
TIMESTAMPS[55]="ends_3m18s"
TIMESTAMPS[56]="ends_3m21s"
TIMESTAMPS[57]="ends_3m25s"
TIMESTAMPS[58]="ends_3m28s"
TIMESTAMPS[59]="ends_3m32s"
TIMESTAMPS[60]="ends_3m36s"
TIMESTAMPS[61]="ends_3m39s"
TIMESTAMPS[62]="ends_3m43s"
TIMESTAMPS[63]="ends_3m46s"
TIMESTAMPS[64]="ends_3m50s"
TIMESTAMPS[65]="ends_3m54s"
TIMESTAMPS[66]="ends_3m57s"
TIMESTAMPS[67]="ends_4m01s"
TIMESTAMPS[68]="ends_4m04s"
TIMESTAMPS[69]="ends_4m08s"
TIMESTAMPS[70]="ends_4m11s"
TIMESTAMPS[71]="ends_4m15s"
TIMESTAMPS[72]="ends_4m19s"
TIMESTAMPS[73]="ends_4m22s"
TIMESTAMPS[74]="ends_4m26s"
TIMESTAMPS[75]="ends_4m29s"
TIMESTAMPS[76]="ends_4m33s"
TIMESTAMPS[77]="ends_4m37s"
TIMESTAMPS[78]="ends_4m40s"
TIMESTAMPS[79]="ends_4m44s"
TIMESTAMPS[80]="ends_4m47s"
TIMESTAMPS[81]="ends_4m51s"
TIMESTAMPS[82]="ends_4m55s"
TIMESTAMPS[83]="ends_4m58s"
TIMESTAMPS[84]="ends_5m02s"
TIMESTAMPS[85]="ends_5m05s"
TIMESTAMPS[86]="ends_5m09s"
TIMESTAMPS[87]="ends_5m13s"
TIMESTAMPS[88]="ends_5m16s"
TIMESTAMPS[89]="ends_5m20s"
TIMESTAMPS[90]="ends_5m23s"
TIMESTAMPS[91]="ends_5m27s"
TIMESTAMPS[92]="ends_5m30s"
TIMESTAMPS[93]="ends_5m34s"
TIMESTAMPS[94]="ends_5m38s"
TIMESTAMPS[95]="ends_5m41s"
TIMESTAMPS[96]="ends_5m45s"
TIMESTAMPS[97]="ends_5m48s"
TIMESTAMPS[98]="ends_5m52s"
TIMESTAMPS[99]="ends_5m56s"
TIMESTAMPS[100]="ends_5m59s"
TIMESTAMPS[101]="ends_6m03s"
TIMESTAMPS[102]="ends_6m06s"
TIMESTAMPS[103]="ends_6m10s"
TIMESTAMPS[104]="ends_6m14s"
TIMESTAMPS[105]="ends_6m17s"
TIMESTAMPS[106]="ends_6m21s"
TIMESTAMPS[107]="ends_6m24s"
TIMESTAMPS[108]="ends_6m28s"
TIMESTAMPS[109]="ends_6m32s"
TIMESTAMPS[110]="ends_6m35s"
TIMESTAMPS[111]="ends_6m39s"
TIMESTAMPS[112]="ends_6m42s"
TIMESTAMPS[113]="ends_6m46s"
TIMESTAMPS[114]="ends_6m50s"
TIMESTAMPS[115]="ends_6m53s"
TIMESTAMPS[116]="ends_6m57s"
TIMESTAMPS[117]="ends_7m00s"
TIMESTAMPS[118]="ends_7m04s"
TIMESTAMPS[119]="ends_7m07s"
TIMESTAMPS[120]="ends_7m11s"

TOTAL=120

count=0
for i in $(seq 1 $TOTAL); do
  gen "$i" "${PROMPTS[$i]}" &
  pids+=($!)
  count=$((count + 1))
  if [ $count -eq $BATCH_SIZE ]; then
    run_batch
    count=0
  fi
done
run_batch

echo ""
echo "All $TOTAL images generated! Check the output_hestia/ folder."
